[build]
builder = "NIXPACKS"

[build.steps]
build = "python -m pip install --upgrade pip && python -m pip install --no-cache-dir setuptools>=69.0.0 wheel>=0.42.0 && python -m pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[services.backend]
tcpProxyApplicationPort = 8000
